apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: default
spec:
  containers:
  - image: 192.168.199.249:5000/helloworld:34
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: helloworld
  restartPolicy: Always
